apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: intent-lab
resources:
- ../../base
replicas:
- name: intent-lab
  count: 5
images:
- name: docker.io/library/nginx
  newTag: 1.27.3
